import type { InferencePassage } from './types';

export const ELA9R11_INFERENCE_PASSAGE: InferencePassage = {
  id: 'ela9r11-most-dangerous-game-opening-001',
  standardCode: 'ELA.9.R.1.1',
  title: 'The Most Dangerous Game',
  author: 'Richard Connell',
  sourceNote: 'Excerpt from O. Henry Memorial Award Prize Stories of 1924. Public domain in the U.S.',
  studentGoal: 'GOGI will read beside you. Stop, say what you suspect, sharpen the thought, and keep reading until the story starts making more sense.',
  chunks: [
    {
      id: 'chunk-1',
      paragraphs: [
        '"Off there to the right--somewhere--is a large island," said Whitney. "It\'s rather a mystery--"',
        '"What island is it?" Rainsford asked.',
        '"The old charts call it Ship-Trap Island," Whitney replied. "A suggestive name, isn\'t it? Sailors have a curious dread of the place. I don\'t know why. Some superstition--"',
        '"Can\'t see it," remarked Rainsford, trying to peer through the dank tropical night that was palpable as it pressed its thick warm blackness in upon the yacht.',
      ],
    },
    {
      id: 'chunk-2',
      paragraphs: [
        '"You\'ve good eyes," said Whitney, with a laugh, "and I\'ve seen you pick off a moose moving in the brown fall bush at four hundred yards, but even you can\'t see four miles or so through a moonless Caribbean night."',
        '"Nor four yards," admitted Rainsford. "Ugh! It\'s like moist black velvet."',
        '"It will be light enough in Rio," promised Whitney. "We should make it in a few days. I hope the jaguar guns have come from Purdey\'s. We should have some good hunting up the Amazon. Great sport, hunting."',
        '"The best sport in the world," agreed Rainsford.',
      ],
    },
    {
      id: 'chunk-3',
      paragraphs: [
        '"For the hunter," amended Whitney. "Not for the jaguar."',
        '"Don\'t talk rot, Whitney," said Rainsford. "You\'re a big-game hunter, not a philosopher. Who cares how a jaguar feels?"',
        '"Perhaps the jaguar does," observed Whitney.',
        '"Bah! They\'ve no understanding."',
        '"Even so, I rather think they understand one thing--fear. The fear of pain and the fear of death."',
      ],
    },
    {
      id: 'chunk-4',
      paragraphs: [
        '"Nonsense," laughed Rainsford. "This hot weather is making you soft, Whitney. Be a realist. The world is made up of two classes--the hunters and the huntees. Luckily, you and I are hunters."',
        '"Do you think we\'ve passed that island yet?"',
        '"I can\'t tell in the dark. I hope so."',
        '"Why?" asked Rainsford.',
        '"The place has a reputation--a bad one."',
      ],
    },
  ],
  inferencePoints: [
    {
      id: 'point-1',
      chunkIndex: 0,
      title: 'Stop 1: The Place',
      anchorText: 'Ship-Trap Island',
      coachingFocus: 'Use a name and a reaction to make a first prediction.',
      independenceLevel: 'guided',
      openingQuestion: 'What do you already suspect about Ship-Trap Island from the name and Whitney\'s reaction?',
      targetUnderstanding: 'The island sounds dangerous because the name suggests ships get trapped there.',
      evidence: ['Ship-Trap Island', 'suggestive name', 'curious dread', 'dank tropical night', 'thick warm blackness'],
      effectSignals: ['danger', 'dangerous', 'trap', 'trapped', 'unsafe', 'fear', 'mystery', 'bad', 'dark', 'scary', 'warning'],
      studentStems: ['I think the island might...', 'The name makes me suspect...', 'Whitney seems...'],
      continueCue: 'Keep that prediction in your head as the next chunk appears.',
      scaffoldPrompts: {
        find_the_move: 'Start simple. The island has "Trap" in the name and Whitney says sailors dread it. What kind of place does that make you imagine?',
        prove_it_with_evidence: 'Point to what made you think that: the name, Whitney\'s reaction, or the darkness around the yacht.',
        explain_the_effect: 'Say the suspicion in your own words. You do not need a perfect essay sentence yet.',
      },
      guidedClose: 'The name and Whitney\'s reaction are enough to form a first prediction: this island is probably dangerous.',
    },
    {
      id: 'point-2',
      chunkIndex: 1,
      title: 'Stop 2: The Mood',
      anchorText: 'moist black velvet',
      coachingFocus: 'Use setting details to name the feeling the author is building.',
      independenceLevel: 'supported',
      openingQuestion: 'After this next chunk, what feeling is Connell building around the yacht and the island?',
      targetUnderstanding: 'The darkness makes the scene feel heavy, closed in, and uneasy.',
      evidence: ['moonless Caribbean night', 'Nor four yards', 'moist black velvet', 'thick warm blackness', 'dank tropical night'],
      effectSignals: ['dark', 'heavy', 'tense', 'uneasy', 'mysterious', 'closed', 'trapped', 'unsafe', 'hard to see', 'foreboding'],
      studentStems: ['The scene feels...', 'The darkness makes it seem...', 'Connell is making the reader feel...'],
      continueCue: 'Now watch how the conversation shifts from the place to how Rainsford thinks.',
      scaffoldPrompts: {
        find_the_move: 'Look at the darkness details. Can they see clearly, or does the night make everything feel hidden?',
        prove_it_with_evidence: 'Pick one phrase about the darkness that gave you that feeling.',
        explain_the_effect: 'Name the feeling first: tense, mysterious, unsafe, heavy, or something close.',
      },
      guidedClose: 'The darkness is doing mood work. It makes the reader feel that the island is hidden and unsafe.',
    },
    {
      id: 'point-3',
      chunkIndex: 2,
      title: 'Stop 3: Rainsford',
      anchorText: 'Who cares how a jaguar feels?',
      coachingFocus: 'Use dialogue to infer how a character thinks.',
      independenceLevel: 'light',
      openingQuestion: 'What do you notice about how Rainsford thinks about hunting here?',
      targetUnderstanding: 'Rainsford sees hunting only from the hunter\'s side and does not imagine the fear of the hunted animal.',
      evidence: ['Who cares how a jaguar feels', 'They\'ve no understanding', 'For the hunter', 'fear of pain', 'fear of death'],
      effectSignals: ['does not care', 'cold', 'confident', 'hunter', 'one-sided', 'no empathy', 'dismisses', 'arrogant', 'blind'],
      studentStems: ['Rainsford seems...', 'He does not really...', 'This shows he thinks...'],
      continueCue: 'Keep that in mind. The next chunk makes his hunter/hunted idea much louder.',
      scaffoldPrompts: {
        find_the_move: 'Do not analyze the whole story yet. Just notice the disagreement: Whitney thinks about the jaguar; Rainsford pushes that away.',
        prove_it_with_evidence: 'Use Rainsford\'s own words if you can, but first say what kind of attitude you hear.',
        explain_the_effect: 'What does this make you understand about Rainsford as a hunter?',
      },
      guidedClose: 'Rainsford is reading the world from the hunter\'s side only. He does not take the hunted animal\'s fear seriously.',
    },
    {
      id: 'point-4',
      chunkIndex: 3,
      title: 'Stop 4: The Warning',
      anchorText: 'the hunters and the huntees',
      coachingFocus: 'Make a prediction from a repeated idea.',
      independenceLevel: 'independent',
      openingQuestion: 'What do you think the story might do with Rainsford\'s idea that people are either "hunters" or "huntees"?',
      targetUnderstanding: 'The line foreshadows that the story may force Rainsford to understand what it feels like to be hunted.',
      evidence: ['hunters and the huntees', 'Luckily, you and I are hunters', 'I hope so', 'a bad one', 'The place has a reputation'],
      effectSignals: ['foreshadow', 'foreshadows', 'warning', 'irony', 'danger', 'switch', 'be hunted', 'hunted', 'expect', 'reversal'],
      studentStems: ['I predict...', 'This might matter because...', 'Rainsford may have to...'],
      continueCue: 'Now you have a full prediction to carry into the rest of the story.',
      scaffoldPrompts: {
        find_the_move: 'Start with his categories. Which side does Rainsford think he is safely on?',
        prove_it_with_evidence: 'Point to the phrase that shows he thinks he is safe: "Luckily, you and I are hunters."',
        explain_the_effect: 'Make a prediction. Why might the author put that confident line next to an island with a bad reputation?',
      },
      guidedClose: 'This is setup. Rainsford is sure he is a hunter, but the island\'s reputation makes that confidence feel unsafe.',
    },
  ],
  closingQuestion: 'Across this excerpt, how does Connell prepare the reader for danger before the main conflict starts? Use one exact detail as proof.',
};
