export type ReadingSkillMove = {
  standardCode: string;
  strandId: string;
  label: string;
  studentMove: string;
  passageMustHave: string[];
  fastStemFocus: string[];
  commonMiss: string;
  scaffold: string;
  masterySignal: string;
};

export const ELA9_READING_SKILL_MOVES: ReadingSkillMove[] = [
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'setting-layer',
    label: 'Setting adds meaning or style',
    studentMove: 'Find the setting detail and explain what it adds to mood, meaning, tone, or style.',
    passageMustHave: ['pointable place/time/weather/social detail', 'effect visible inside the excerpt'],
    fastStemFocus: ['setting detail effect', 'layer of meaning', 'mood or tone from setting'],
    commonMiss: 'Student describes where the scene happens but misses why that detail matters.',
    scaffold: 'Point to the setting detail. Then finish: this place/time detail creates ___ because ___.',
    masterySignal: 'Student explains how setting adds a meaning or style layer with exact evidence.',
  },
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'plot-conflict-layer',
    label: 'Plot or conflict adds meaning',
    studentMove: 'Explain how the event, conflict, choice, or consequence adds a deeper layer.',
    passageMustHave: ['event, conflict, choice, reversal, or consequence', 'meaning beyond plot summary'],
    fastStemFocus: ['conflict effect', 'plot detail meaning', 'author purpose for an event'],
    commonMiss: 'Student summarizes the event instead of explaining the meaning created by it.',
    scaffold: 'Name the conflict or event. Then ask: what does this moment reveal, pressure, or change?',
    masterySignal: 'Student connects plot/conflict evidence to meaning, tension, or theme.',
  },
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'characterization-layer',
    label: 'Characterization adds meaning',
    studentMove: 'Use a character’s action, thought, speech, or description to explain a deeper meaning.',
    passageMustHave: ['character action/thought/speech/description', 'clear inference about character or theme'],
    fastStemFocus: ['character evidence', 'characterization effect', 'meaning from action or speech'],
    commonMiss: 'Student labels the character with a trait but does not prove the layer of meaning.',
    scaffold: 'Point to what the character does or says. Then explain what it reveals and why it matters.',
    masterySignal: 'Student uses character evidence to explain meaning, style, or theme.',
  },
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'point-of-view-layer',
    label: 'Point of view adds meaning',
    studentMove: 'Explain how the narrator or viewpoint shapes what the reader understands.',
    passageMustHave: ['visible narrator/viewpoint clue', 'reader understanding shaped by that viewpoint'],
    fastStemFocus: ['point of view effect', 'reader understanding', 'narrator lens'],
    commonMiss: 'Student identifies who is telling the story but not how that lens changes meaning.',
    scaffold: 'Ask: who sees this moment, what do they notice, and how does that shape the reader?',
    masterySignal: 'Student connects viewpoint evidence to meaning, tone, or reader understanding.',
  },
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'theme-tone-layer',
    label: 'Theme or tone layer',
    studentMove: 'Explain how a key element points to theme or creates tone.',
    passageMustHave: ['key element with thematic or tonal force', 'evidence that shows author attitude or message'],
    fastStemFocus: ['theme clue', 'tone clue', 'layer of meaning'],
    commonMiss: 'Student chooses a broad theme or tone word without proving it from the element.',
    scaffold: 'Name the element. Then finish: this points to the idea/attitude that ___.',
    masterySignal: 'Student explains a theme or tone layer with evidence from a literary element.',
  },
  {
    standardCode: 'ELA.9.R.1.1',
    strandId: 'style-technique-layer',
    label: 'Style technique adds meaning',
    studentMove: 'Connect diction, syntax, grammar, or figurative language to the author’s effect.',
    passageMustHave: ['pointable diction, syntax, grammar, or figurative language', 'clear author voice/effect'],
    fastStemFocus: ['style effect', 'diction/syntax effect', 'author voice'],
    commonMiss: 'Student notices the technique but gives a generic effect.',
    scaffold: 'Name the style move. Then ask what it makes the reader hear, feel, or notice.',
    masterySignal: 'Student explains how style supports meaning or author voice.',
  },
  {
    standardCode: 'ELA.9.R.1.2',
    strandId: 'universal-theme',
    label: 'Universal theme',
    studentMove: 'Turn the topic into a transferable idea about people, choices, life, or society.',
    passageMustHave: ['topic with transferable meaning', 'evidence that supports a universal statement'],
    fastStemFocus: ['universal theme', 'theme statement', 'theme beyond plot'],
    commonMiss: 'Student gives a one-word topic or a plot-specific lesson.',
    scaffold: 'Start with the topic. Now write a sentence that could be true outside this story.',
    masterySignal: 'Student states a universal theme and proves it with passage evidence.',
  },
  {
    standardCode: 'ELA.9.R.1.2',
    strandId: 'theme-development-moments',
    label: 'Theme developed through moments',
    studentMove: 'Turn the topic into a life lesson and prove it with more than one moment.',
    passageMustHave: ['clear topic', 'two or more details developing the same universal idea'],
    fastStemFocus: ['theme statement', 'theme evidence', 'theme development across moments'],
    commonMiss: 'Student picks a topic or moral-sounding statement that the passage does not actually develop.',
    scaffold: 'Name the topic in one word. Now turn it into a sentence about people, choices, or life. Prove it twice.',
    masterySignal: 'Student selects a universal theme and matches it to evidence that develops it.',
  },
  {
    standardCode: 'ELA.9.R.1.2',
    strandId: 'theme-through-conflict',
    label: 'Theme through conflict or consequence',
    studentMove: 'Explain how conflict, choice, consequence, or realization develops the theme.',
    passageMustHave: ['conflict, choice, consequence, or realization', 'theme visible through the moment'],
    fastStemFocus: ['theme development', 'conflict and theme', 'consequence and theme'],
    commonMiss: 'Student treats the conflict as action only and misses the lesson it develops.',
    scaffold: 'Name the conflict or consequence. Then ask what idea about life it teaches.',
    masterySignal: 'Student explains how conflict or consequence develops a universal theme.',
  },
  {
    standardCode: 'ELA.9.R.1.3',
    strandId: 'narrator-perspective',
    label: 'Narrator perspective shapes understanding',
    studentMove: 'Explain how the narrator or speaker’s lens shapes what the reader notices or understands.',
    passageMustHave: ['clear narrator or speaker lens', 'reader understanding shaped by what is noticed, withheld, or emphasized'],
    fastStemFocus: ['narrator perspective', 'speaker attitude', 'reader understanding'],
    commonMiss: 'Student identifies who is speaking but misses how the perspective changes meaning.',
    scaffold: 'Ask: who is filtering this moment, what do they notice, and what does that make the reader understand?',
    masterySignal: 'Student explains how narrator or speaker perspective shapes reader understanding.',
  },
  {
    standardCode: 'ELA.9.R.1.3',
    strandId: 'irony-reversal-contrast',
    label: 'Irony through contrast or reversal',
    studentMove: 'Compare what is said with what the reader understands.',
    passageMustHave: ['speaker-reader gap, reversal, exaggeration, or contrast', 'effect visible without outside context'],
    fastStemFocus: ['narrator perspective', 'irony through contrast', 'satirical effect'],
    commonMiss: 'Student reads the line straight instead of noticing the gap or reversal.',
    scaffold: 'Separate two columns: what the speaker thinks, and what the reader understands.',
    masterySignal: 'Student explains the contrast that creates irony, satire, or perspective-based meaning.',
  },
  {
    standardCode: 'ELA.9.R.1.3',
    strandId: 'satire-exaggeration-ridicule',
    label: 'Satire through exaggeration or false logic',
    studentMove: 'Explain how exaggeration, fake seriousness, or ridiculous logic criticizes a real problem.',
    passageMustHave: ['exaggeration, mock seriousness, or absurd logic', 'target of criticism visible in the excerpt'],
    fastStemFocus: ['satire', 'exaggeration', 'author criticism', 'ironic speaker'],
    commonMiss: 'Student treats the satirical speaker as sincere and misses the criticism.',
    scaffold: 'Ask: what sounds serious on the surface, what is actually absurd, and what is being criticized?',
    masterySignal: 'Student explains how satire criticizes a problem through exaggeration, contrast, or false logic.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'in-medias-res',
    label: 'In medias res',
    studentMove: 'Explain how beginning in the middle of action shapes structure or tension.',
    passageMustHave: ['story begins after key action has already started', 'reader must infer the situation from clues'],
    fastStemFocus: ['epic structure', 'middle of action', 'reader orientation'],
    commonMiss: 'Student summarizes the event but misses how the opening structure affects the reader.',
    scaffold: 'Ask: what has already happened, what must the reader infer, and why begin here?',
    masterySignal: 'Student explains how the in medias res structure affects meaning, tension, or reader understanding.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'divine-intervention',
    label: 'Divine intervention',
    studentMove: 'Explain how a god, prayer, prophecy, or supernatural force shapes epic action.',
    passageMustHave: ['god/goddess, prayer, prophecy, fate, or supernatural force', 'clear effect on action, character, or theme'],
    fastStemFocus: ['epic convention', 'divine influence', 'theme or plot effect'],
    commonMiss: 'Student notices the god or prayer but treats it as background instead of an epic convention.',
    scaffold: 'Name the divine force. Then finish: this changes the action by ___ and shows ___.',
    masterySignal: 'Student connects divine influence to character, structure, or theme.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'epic-hero-traits',
    label: 'Epic hero traits',
    studentMove: 'Use evidence to explain the hero trait being developed.',
    passageMustHave: ['hero action, choice, speech, or challenge', 'trait such as courage, pride, loyalty, endurance, or cleverness'],
    fastStemFocus: ['hero characterization', 'epic values', 'trait evidence'],
    commonMiss: 'Student calls the character heroic without proving the specific trait.',
    scaffold: 'Point to the action first. Then name the trait and explain how the action proves it.',
    masterySignal: 'Student explains a hero trait using exact evidence from the epic.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'quest-journey-structure',
    label: 'Quest or journey structure',
    studentMove: 'Track the journey stage or obstacle and explain how it develops the epic.',
    passageMustHave: ['journey, obstacle, return, test, or recognition moment', 'effect on character or theme'],
    fastStemFocus: ['quest structure', 'obstacle or test', 'journey meaning'],
    commonMiss: 'Student retells the event without explaining its role in the larger journey.',
    scaffold: 'Label the stage: departure, test, obstacle, return, or recognition. Then explain why it matters.',
    masterySignal: 'Student connects a journey stage to character development or theme.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'ritual-speech-oath',
    label: 'Ritual, speech, or oath',
    studentMove: 'Explain how a formal epic moment reveals values or theme.',
    passageMustHave: ['speech, prayer, oath, offering, feast, burial, hospitality, or ritual', 'value or theme revealed by the ritual'],
    fastStemFocus: ['epic convention', 'ritual or speech effect', 'cultural value'],
    commonMiss: 'Student treats the ritual as plot decoration instead of evidence of epic values.',
    scaffold: 'Name the formal action. Then ask: what value does this moment show?',
    masterySignal: 'Student explains how a ritual, oath, or speech develops epic values or theme.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'theme-through-heroic-action',
    label: 'Theme through heroic action',
    studentMove: 'Explain how a heroic action develops a theme such as honor, fate, loyalty, or homecoming.',
    passageMustHave: ['heroic action or choice', 'theme visible through the consequence or value'],
    fastStemFocus: ['epic theme', 'heroic action', 'theme evidence'],
    commonMiss: 'Student names a heroic action but does not explain the theme it develops.',
    scaffold: 'Name the action. Then finish: this develops the theme of ___ because ___.',
    masterySignal: 'Student connects heroic action to an epic theme with evidence.',
  },
  {
    standardCode: 'ELA.9.R.1.4',
    strandId: 'elevated-style-epic-simile',
    label: 'Elevated style and epic simile',
    studentMove: 'Explain how formal language, repeated phrasing, invocation, or extended comparison creates epic style.',
    passageMustHave: ['formal/elevated diction, invocation, repeated phrasing, or extended comparison', 'effect on style or meaning'],
    fastStemFocus: ['epic style', 'epic simile', 'formal language effect'],
    commonMiss: 'Student labels the comparison or formal wording but misses its epic effect.',
    scaffold: 'Name the style move. Then explain what it makes the action or character seem like.',
    masterySignal: 'Student explains how elevated style or epic simile shapes meaning.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'chronological-sequence',
    label: 'Chronological or sequence structure',
    studentMove: 'Explain how time order, steps, or sequence helps the author develop meaning or purpose.',
    passageMustHave: ['time-order signal or sequence of events/ideas', 'purpose for the order'],
    fastStemFocus: ['chronological structure', 'sequence effect', 'order of ideas'],
    commonMiss: 'Student notices what happened first but does not explain why the order matters.',
    scaffold: 'Mark the sequence words. Then ask: why did the author put the ideas in this order?',
    masterySignal: 'Student explains how chronological or sequence structure develops purpose or meaning.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'cause-effect-structure',
    label: 'Cause and effect structure',
    studentMove: 'Explain how the author connects a cause, condition, or problem to a result.',
    passageMustHave: ['cause/condition/result signal', 'clear effect on meaning, argument, or purpose'],
    fastStemFocus: ['cause and effect', 'result of condition', 'why structure matters'],
    commonMiss: 'Student summarizes the cause or result without explaining how the relationship builds meaning.',
    scaffold: 'Circle the cause. Box the result. Then explain why the author links them.',
    masterySignal: 'Student connects cause/effect structure to author purpose or meaning.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'compare-contrast-structure',
    label: 'Compare and contrast structure',
    studentMove: 'Explain how a contrast or comparison clarifies the author’s point.',
    passageMustHave: ['two ideas/groups/actions contrasted or compared', 'meaning clarified by the contrast'],
    fastStemFocus: ['comparison effect', 'contrast effect', 'purpose of comparing'],
    commonMiss: 'Student names both sides but misses how the contrast sharpens the point.',
    scaffold: 'Make two columns. Then explain what the reader understands because of the contrast.',
    masterySignal: 'Student explains how comparison or contrast structure develops purpose or meaning.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'problem-solution-structure',
    label: 'Problem and solution structure',
    studentMove: 'Identify the problem and explain how the proposed response develops the author’s purpose.',
    passageMustHave: ['problem/issue', 'solution/proposal/response', 'author purpose visible in the structure'],
    fastStemFocus: ['problem-solution', 'proposal purpose', 'issue and response'],
    commonMiss: 'Student lists the problem and solution but does not explain the author’s purpose for pairing them.',
    scaffold: 'Name the problem first. Then name the response and explain what the pairing makes clear.',
    masterySignal: 'Student explains how problem/solution structure supports author purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'example-evidence-structure',
    label: 'Example or evidence structure',
    studentMove: 'Explain how examples, data, or evidence develop the author’s point.',
    passageMustHave: ['example, statistic, evidence, or illustration', 'clear point the evidence supports'],
    fastStemFocus: ['example purpose', 'evidence structure', 'supporting detail effect'],
    commonMiss: 'Student picks a true detail but misses the job it does in the paragraph.',
    scaffold: 'Ask: what point is the example proving, illustrating, or making easier to understand?',
    masterySignal: 'Student explains how examples or evidence structure develops meaning or purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.1',
    strandId: 'opening-closing-shift',
    label: 'Opening, closing, or shift structure',
    studentMove: 'Explain how an introduction, transition, shift, or conclusion guides the reader.',
    passageMustHave: ['opening/closing signal or shift', 'reader guidance or purpose created by placement'],
    fastStemFocus: ['opening purpose', 'conclusion effect', 'shift in structure'],
    commonMiss: 'Student treats the paragraph as isolated and misses its placement or transition job.',
    scaffold: 'Ask: is this part introducing, shifting, narrowing, summarizing, or concluding the idea?',
    masterySignal: 'Student explains how an opening, closing, transition, or shift develops purpose or meaning.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'strong-vs-weak-evidence',
    label: 'Central idea with strong evidence',
    studentMove: 'Say the big idea, then choose the proof that actually develops it.',
    passageMustHave: ['clear central idea', 'strong evidence and true-but-weaker details'],
    fastStemFocus: ['central idea', 'best evidence', 'support development'],
    commonMiss: 'Student picks a true detail that is related but does not prove the central idea.',
    scaffold: 'Before choosing evidence, say the central idea in plain words. Then ask which detail makes that idea stronger.',
    masterySignal: 'Student pairs a central idea with evidence and explains how the evidence develops it.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'central-idea-stated-implied',
    label: 'Central idea stated or implied',
    studentMove: 'Determine the central idea by separating the author’s main point from supporting details.',
    passageMustHave: ['one clear controlling idea', 'details that point back to that idea'],
    fastStemFocus: ['central idea', 'main point', 'controlling idea'],
    commonMiss: 'Student chooses a detail that is true but too narrow to be the central idea.',
    scaffold: 'Ask: what is this whole excerpt mostly proving, not just mentioning?',
    masterySignal: 'Student states the central idea accurately and avoids choosing a single detail.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'evidence-develops-central-idea',
    label: 'Evidence develops central idea',
    studentMove: 'Explain how a specific detail, example, or reason develops the central idea.',
    passageMustHave: ['central idea', 'specific evidence that extends, proves, or clarifies it'],
    fastStemFocus: ['how evidence develops idea', 'supporting detail effect', 'evidence purpose'],
    commonMiss: 'Student says the evidence is related but does not explain the job it does.',
    scaffold: 'Use the frame: this evidence develops the central idea by showing ___.',
    masterySignal: 'Student explains how evidence strengthens, clarifies, or extends the central idea.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'best-evidence-for-claim',
    label: 'Best evidence for a claim',
    studentMove: 'Choose the piece of evidence that most directly proves a stated central claim.',
    passageMustHave: ['claim or central idea', 'multiple evidence options with one strongest support'],
    fastStemFocus: ['best evidence', 'strongest support', 'claim proof'],
    commonMiss: 'Student chooses interesting evidence instead of the evidence that most directly proves the claim.',
    scaffold: 'Test each option: does this prove the claim, or is it only nearby information?',
    masterySignal: 'Student selects the strongest evidence for a claim and can explain why it is strongest.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'detail-vs-central-idea',
    label: 'Detail versus central idea',
    studentMove: 'Reject details that are true but too small, off-track, or weak for the central idea.',
    passageMustHave: ['central idea', 'true details that vary in relevance or strength'],
    fastStemFocus: ['true but weak detail', 'irrelevant evidence', 'central idea boundary'],
    commonMiss: 'Student assumes any true sentence from the passage must support the central idea.',
    scaffold: 'Ask: is this detail proving the big idea, or is it just a fact from the text?',
    masterySignal: 'Student distinguishes strong support from true-but-weak or off-track details.',
  },
  {
    standardCode: 'ELA.9.R.2.2',
    strandId: 'central-idea-development-across-paragraphs',
    label: 'Central idea across paragraphs',
    studentMove: 'Track how two or more paragraphs build the central idea together.',
    passageMustHave: ['two-paragraph development', 'each paragraph adds a different support move'],
    fastStemFocus: ['development across text', 'paragraph relationship', 'idea progression'],
    commonMiss: 'Student reads one paragraph in isolation and misses how the ideas build together.',
    scaffold: 'Label what paragraph 1 adds, label what paragraph 2 adds, then explain the connection.',
    masterySignal: 'Student explains how multiple paragraphs work together to develop one central idea.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'logos-ethos-pathos',
    label: 'Rhetorical appeal connected to purpose',
    studentMove: 'Name the persuasive move and explain why it helps the author.',
    passageMustHave: ['facts, credibility, emotion, analogy, or vivid language', 'clear author purpose'],
    fastStemFocus: ['appeal type', 'audience or purpose fit', 'figurative language for persuasion'],
    commonMiss: 'Student names the topic but not the persuasive move or purpose.',
    scaffold: 'Ask: is the author using facts, trust, feelings, or vivid language? Then ask why that move fits the purpose.',
    masterySignal: 'Student identifies the appeal and explains how it helps achieve purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'logos-evidence-reasoning',
    label: 'Logos: evidence and reasoning',
    studentMove: 'Explain how facts, examples, calculations, or reasoning help the author persuade.',
    passageMustHave: ['facts, numbers, examples, or logical chain', 'clear persuasive purpose'],
    fastStemFocus: ['logos', 'reasoning effect', 'evidence for purpose'],
    commonMiss: 'Student names a fact but does not explain how the fact supports the author’s purpose.',
    scaffold: 'Ask: what proof is the author using, and what does that proof make the reader believe?',
    masterySignal: 'Student explains how evidence or reasoning helps the author achieve purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'ethos-credibility-authority',
    label: 'Ethos: credibility and authority',
    studentMove: 'Explain how credibility, expertise, fairness, or moral authority supports purpose.',
    passageMustHave: ['speaker credibility, expert reference, moral authority, or fair-minded qualification', 'purpose connected to trust'],
    fastStemFocus: ['ethos', 'credibility', 'authority and purpose'],
    commonMiss: 'Student treats the reference or credential as background instead of explaining how it builds trust.',
    scaffold: 'Ask: why should the reader trust this speaker or source right now?',
    masterySignal: 'Student connects credibility or authority to the author’s persuasive purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'pathos-emotional-appeal',
    label: 'Pathos: emotional appeal',
    studentMove: 'Explain how emotional language, vivid suffering, fear, hope, or urgency supports purpose.',
    passageMustHave: ['emotionally charged wording or vivid human impact', 'reader feeling tied to purpose'],
    fastStemFocus: ['pathos', 'emotional effect', 'reader feeling and purpose'],
    commonMiss: 'Student identifies emotion but does not explain why the author wants that feeling.',
    scaffold: 'Ask: what feeling is the author creating, and what action or belief does that feeling support?',
    masterySignal: 'Student explains how emotion helps the author persuade or emphasize purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'rhetorical-question-repetition',
    label: 'Rhetorical question or repetition',
    studentMove: 'Explain how a question, repeated phrase, or parallel wording guides the reader toward the purpose.',
    passageMustHave: ['rhetorical question, repetition, or parallel structure', 'effect on reader focus or emphasis'],
    fastStemFocus: ['rhetorical question', 'repetition effect', 'parallel structure purpose'],
    commonMiss: 'Student notices repeated words but misses how repetition pressures or focuses the reader.',
    scaffold: 'Ask: what idea is repeated or asked, and why does the author want the reader focused there?',
    masterySignal: 'Student explains how repeated or question-based rhetoric supports purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'figurative-language-purpose',
    label: 'Figurative language for purpose',
    studentMove: 'Explain how figurative or vivid language helps the author achieve an informational purpose.',
    passageMustHave: ['analogy, comparison, metaphor, image, or vivid diction', 'purpose beyond decoration'],
    fastStemFocus: ['figurative language in informational text', 'vivid language purpose', 'reader understanding'],
    commonMiss: 'Student labels the language as figurative but gives a generic effect.',
    scaffold: 'Ask: what idea does the image make easier to understand, feel, or believe?',
    masterySignal: 'Student connects figurative or vivid language to author purpose.',
  },
  {
    standardCode: 'ELA.9.R.2.3',
    strandId: 'purpose-fit-rhetorical-choice',
    label: 'Rhetorical choice fits purpose',
    studentMove: 'Explain why the author chose a specific rhetorical move for a specific audience or purpose.',
    passageMustHave: ['clear author purpose', 'rhetorical move that fits that purpose'],
    fastStemFocus: ['purpose fit', 'audience effect', 'why this rhetorical move'],
    commonMiss: 'Student identifies the move but cannot explain why it fits the author’s purpose.',
    scaffold: 'Use the frame: the author uses ___ because the reader needs to ___.',
    masterySignal: 'Student explains why a rhetorical choice fits the author’s purpose and audience.',
  },
  {
    standardCode: 'ELA.9.R.2.4',
    strandId: 'identify-opposing-claims',
    label: 'Identify opposing claims',
    studentMove: 'Name each side’s claim before judging either argument.',
    passageMustHave: ['two claims or pairable arguments', 'evidence that can be sorted by side'],
    fastStemFocus: ['opposing claims', 'claim comparison', 'same topic different positions'],
    commonMiss: 'Student blends both arguments together before identifying each separate position.',
    scaffold: 'Make two columns: Passage A claims ___. Passage B claims ___. They disagree about ___.',
    masterySignal: 'Student accurately identifies both opposing claims and the issue they disagree about.',
  },
  {
    standardCode: 'ELA.9.R.2.4',
    strandId: 'compare-evidence-development',
    label: 'Compare evidence development',
    studentMove: 'Keep each side separate, then compare how each author develops support.',
    passageMustHave: ['two claims or pairable arguments', 'evidence that can be sorted by side'],
    fastStemFocus: ['evidence comparison', 'support development', 'which side develops the claim'],
    commonMiss: 'Student assigns evidence to the wrong side or chooses evidence that is true but weak.',
    scaffold: 'List each side’s claim and evidence. Then ask which evidence develops the claim more directly.',
    masterySignal: 'Student compares how both arguments use evidence to develop their claims.',
  },
  {
    standardCode: 'ELA.9.R.2.4',
    strandId: 'evaluate-validity',
    label: 'Evaluate claim validity',
    studentMove: 'Judge whether the claim is logical and supported by relevant evidence.',
    passageMustHave: ['two claims', 'support that can be tested for relevance or logic'],
    fastStemFocus: ['validity', 'logical support', 'relevant evidence'],
    commonMiss: 'Student chooses the claim they agree with instead of judging whether the support proves it.',
    scaffold: 'Ask: does this evidence actually prove the claim, or is it only related to the topic?',
    masterySignal: 'Student evaluates validity by connecting each claim to relevant, logical support.',
  },
  {
    standardCode: 'ELA.9.R.2.4',
    strandId: 'evaluate-effectiveness',
    label: 'Evaluate argument effectiveness',
    studentMove: 'Judge which argument is more convincing for the audience and explain why.',
    passageMustHave: ['two arguments', 'different persuasive choices or support quality'],
    fastStemFocus: ['effectiveness', 'stronger argument', 'audience and support'],
    commonMiss: 'Student says an argument is stronger because it sounds intense, not because it is better supported.',
    scaffold: 'Ask which side gives clearer reasons, better evidence, or a more convincing response to the audience.',
    masterySignal: 'Student explains why one argument is more effective using evidence from both sides.',
  },
  {
    standardCode: 'ELA.9.R.2.4',
    strandId: 'response-counterclaim',
    label: 'Response to counterclaim',
    studentMove: 'Explain how one author answers, limits, or challenges the opposing argument.',
    passageMustHave: ['counterclaim or criticism', 'response, qualification, or rebuttal'],
    fastStemFocus: ['counterclaim', 'response to opposition', 'qualification or rebuttal'],
    commonMiss: 'Student notices two positions but misses how one side directly answers the other.',
    scaffold: 'Name the criticism first. Then explain how the response challenges, limits, or answers it.',
    masterySignal: 'Student explains how a response or qualification affects the argument’s strength.',
  },
  {
    standardCode: 'ELA.9.R.3.1',
    strandId: 'metaphor-simile',
    label: 'Metaphor and simile',
    studentMove: 'Find the comparison, explain the literal meaning, then explain the effect.',
    passageMustHave: ['pointable comparison', 'meaning recoverable from context', 'literal details for distractors'],
    fastStemFocus: ['comparison in context', 'figurative meaning', 'effect on mood or understanding'],
    commonMiss: 'Student names the device or mood word without explaining what the comparison suggests.',
    scaffold: 'Ask: what two things are being connected? What does that connection suggest? What effect does it create?',
    masterySignal: 'Student explains the comparison, its meaning, and its effect using exact evidence.',
  },
  {
    standardCode: 'ELA.9.R.3.1',
    strandId: 'personification-effect',
    label: 'Personification effect',
    studentMove: 'Explain how giving human action or feeling to a nonhuman thing shapes mood or meaning.',
    passageMustHave: ['nonhuman object, place, force, or idea acting human', 'clear mood or meaning effect'],
    fastStemFocus: ['personification effect', 'mood from nonhuman action', 'reader understanding'],
    commonMiss: 'Student notices the object but misses how the human-like action changes the mood or meaning.',
    scaffold: 'Name the nonhuman thing. Name the human action. Then explain what feeling or idea it creates.',
    masterySignal: 'Student explains how personification creates mood, meaning, or reader effect with exact evidence.',
  },
  {
    standardCode: 'ELA.9.R.3.1',
    strandId: 'imagery-sensory-language',
    label: 'Imagery and sensory language',
    studentMove: 'Use sensory details to explain the atmosphere or reader effect.',
    passageMustHave: ['visual, sound, touch, smell, or taste detail cluster', 'clear atmosphere or meaning effect'],
    fastStemFocus: ['imagery effect', 'sensory detail', 'mood or reader understanding'],
    commonMiss: 'Student describes the image literally but does not explain what it makes the reader feel or notice.',
    scaffold: 'Name the sense first. Then finish: this image makes the scene feel ___ because ___.',
    masterySignal: 'Student connects sensory evidence to a specific mood, meaning, or reader effect.',
  },
  {
    standardCode: 'ELA.9.R.3.1',
    strandId: 'symbol-object-meaning',
    label: 'Symbol or object meaning',
    studentMove: 'Explain how an object, color, animal, place, or repeated image suggests a larger meaning.',
    passageMustHave: ['pointable object/image', 'meaning beyond literal object', 'context evidence for the meaning'],
    fastStemFocus: ['symbol meaning', 'object/image effect', 'larger idea from image'],
    commonMiss: 'Student identifies the object but treats it only literally.',
    scaffold: 'Point to the object. Ask what idea or feeling it stands for in this moment.',
    masterySignal: 'Student explains how an image or object creates meaning beyond its literal role.',
  },
  {
    standardCode: 'ELA.9.R.3.1',
    strandId: 'mood-shift-effect',
    label: 'Mood shift through language',
    studentMove: 'Track how word choice or imagery creates or changes the mood.',
    passageMustHave: ['clear mood words/images', 'before-and-after or pressure/change inside the excerpt'],
    fastStemFocus: ['mood creation', 'mood shift', 'word choice effect'],
    commonMiss: 'Student names a feeling but cannot prove where the mood comes from or how it changes.',
    scaffold: 'Underline the mood words. Name the mood. Then explain what changed or intensified.',
    masterySignal: 'Student proves a mood or mood shift with exact language from the excerpt.',
  },
  {
    standardCode: 'ELA.9.R.3.2',
    strandId: 'chunk-complex-syntax',
    label: 'Chunk complex syntax',
    studentMove: 'Break the sentence into smaller parts and restate each part accurately.',
    passageMustHave: ['long, inverted, or layered sentence', 'stable meaning recoverable from context'],
    fastStemFocus: ['paraphrase', 'sentence meaning', 'preserve original idea'],
    commonMiss: 'Student changes the meaning while trying to simplify the sentence.',
    scaffold: 'Circle the subject and action. Slash the sentence into chunks. Restate one chunk at a time.',
    masterySignal: 'Student paraphrases complex syntax without adding, deleting, or distorting meaning.',
  },
  {
    standardCode: 'ELA.9.R.3.2',
    strandId: 'preserve-original-meaning',
    label: 'Preserve original meaning',
    studentMove: 'Choose the paraphrase that keeps the same meaning as the original.',
    passageMustHave: ['clear original meaning', 'distractors that add, omit, or twist meaning'],
    fastStemFocus: ['accurate paraphrase', 'same meaning', 'avoid distortion'],
    commonMiss: 'Student chooses a simpler sentence that sounds right but changes the author’s idea.',
    scaffold: 'Check every important idea: did the paraphrase keep it, add to it, or leave it out?',
    masterySignal: 'Student selects or writes a paraphrase that preserves the original meaning.',
  },
  {
    standardCode: 'ELA.9.R.3.2',
    strandId: 'translate-archaic-or-formal-language',
    label: 'Translate archaic or formal language',
    studentMove: 'Use context to restate older, formal, poetic, or unfamiliar wording in plain language.',
    passageMustHave: ['older, formal, poetic, or unfamiliar wording', 'context that supports a stable restatement'],
    fastStemFocus: ['paraphrase formal language', 'modern restatement', 'preserve meaning'],
    commonMiss: 'Student modernizes the words but changes the author’s meaning.',
    scaffold: 'Keep the author’s idea. Replace only the hard wording with plain language.',
    masterySignal: 'Student translates formal or archaic wording without distorting meaning.',
  },
  {
    standardCode: 'ELA.9.R.3.2',
    strandId: 'paraphrase-claim-or-theme',
    label: 'Paraphrase claim or theme',
    studentMove: 'Restate the claim, central idea, theme, or speaker point clearly and accurately.',
    passageMustHave: ['claim, theme, central idea, or speaker point', 'details that confirm the intended meaning'],
    fastStemFocus: ['paraphrase claim', 'paraphrase theme', 'accurate main idea restatement'],
    commonMiss: 'Student paraphrases a detail but misses the larger claim or point.',
    scaffold: 'Ask: what is the author or speaker really saying? Then restate it without extra ideas.',
    masterySignal: 'Student accurately paraphrases a claim, theme, or main point.',
  },
  {
    standardCode: 'ELA.9.V.1.1',
    strandId: 'tier-two-academic-word',
    label: 'Academic vocabulary in context',
    studentMove: 'Use context to determine the meaning of a transferable academic word.',
    passageMustHave: ['Tier 2 academic word', 'nearby clue or sentence logic', 'useful transfer value'],
    fastStemFocus: ['academic word meaning', 'context fit', 'precise meaning'],
    commonMiss: 'Student picks a familiar synonym that does not fit the sentence.',
    scaffold: 'Replace the word with your guess, reread the sentence, and test whether the idea still works.',
    masterySignal: 'Student uses context to choose a precise academic meaning.',
  },
  {
    standardCode: 'ELA.9.V.1.1',
    strandId: 'word-family-relationship',
    label: 'Word family relationship',
    studentMove: 'Use related word forms to understand and use academic vocabulary accurately.',
    passageMustHave: ['academic word with related forms', 'context that clarifies the word family'],
    fastStemFocus: ['word family', 'related form', 'academic vocabulary use'],
    commonMiss: 'Student recognizes the base word but uses the wrong form or meaning.',
    scaffold: 'List the related forms. Then choose the form and meaning that fits this sentence.',
    masterySignal: 'Student uses a word family relationship to determine and apply meaning.',
  },
  {
    standardCode: 'ELA.9.V.1.1',
    strandId: 'academic-tone-precision',
    label: 'Academic tone and precision',
    studentMove: 'Choose the precise academic word that fits the author’s meaning and tone.',
    passageMustHave: ['precise academic word', 'near synonyms with different tone or meaning'],
    fastStemFocus: ['precise vocabulary', 'tone fit', 'academic register'],
    commonMiss: 'Student picks a familiar synonym that is less precise or has the wrong tone.',
    scaffold: 'Test each synonym in the sentence. Keep the one that matches both meaning and tone.',
    masterySignal: 'Student selects or uses academic vocabulary with precision.',
  },
  {
    standardCode: 'ELA.9.R.3.3',
    strandId: 'adaptation-same-and-changed',
    label: 'Adaptation: same and changed',
    studentMove: 'Notice what stayed the same, what changed, and how the meaning changed.',
    passageMustHave: ['source pattern or provided source summary', 'adapted version with visible change'],
    fastStemFocus: ['source pattern', 'adaptation change', 'changed meaning or effect'],
    commonMiss: 'Student notices the shared element but misses the changed meaning.',
    scaffold: 'Use three boxes: same, changed, new effect.',
    masterySignal: 'Student compares source and adaptation by naming the shared element and changed meaning.',
  },
  {
    standardCode: 'ELA.9.R.3.4',
    strandId: 'reader-belief-feeling-notice',
    label: 'Rhetoric and reader effect',
    studentMove: 'Explain what the wording makes the reader believe, feel, or notice.',
    passageMustHave: ['pointable rhetorical move', 'clear reader effect or purpose'],
    fastStemFocus: ['rhetorical effect', 'reader belief/feeling/focus', 'purpose connection'],
    commonMiss: 'Student identifies the quote but misses its intended effect on the reader.',
    scaffold: 'After the quote, finish this sentence: the author wants the reader to ___.',
    masterySignal: 'Student explains the rhetorical move and connects it to reader effect or author purpose.',
  },
  {
    standardCode: 'ELA.9.V.1.2',
    strandId: 'prefix-root-suffix',
    label: 'Word parts in context',
    studentMove: 'Break the word into parts, define the parts, then test the meaning in context.',
    passageMustHave: ['target word with useful prefix, root, or suffix', 'surrounding context that confirms meaning'],
    fastStemFocus: ['word parts', 'origin or related word clue', 'context confirmation'],
    commonMiss: 'Student guesses from the sentence only or uses a familiar but wrong word part.',
    scaffold: 'Split the word. Define each part. Then reread the sentence to test the meaning.',
    masterySignal: 'Student uses word parts and context together to determine meaning.',
  },
  {
    standardCode: 'ELA.9.V.1.3',
    strandId: 'context-clues',
    label: 'Word or phrase meaning in context',
    studentMove: 'Use nearby words to choose the meaning that fits this sentence, not every sentence.',
    passageMustHave: ['target word or phrase', 'nearby clues', 'plausible wrong meanings'],
    fastStemFocus: ['context clue', 'connotation/denotation', 'word relationship'],
    commonMiss: 'Student chooses a synonym that is familiar but wrong for this context.',
    scaffold: 'Replace the word with each answer choice. Keep the one that fits the sentence and tone.',
    masterySignal: 'Student selects the context-specific meaning and explains the clue that proves it.',
  },
];

function normalize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

export function getReadingSkillMovesForStandard(standardCode: string) {
  return ELA9_READING_SKILL_MOVES.filter((move) => move.standardCode === standardCode);
}

export function getReadingSkillMove(args: {
  standardCode: string;
  strandId?: string | null;
  strandLabel?: string | null;
  targetSkill?: string | null;
}) {
  const moves = getReadingSkillMovesForStandard(args.standardCode);
  if (!moves.length) return null;

  const strandId = normalize(args.strandId ?? '');
  const label = normalize(`${args.strandLabel ?? ''} ${args.targetSkill ?? ''}`);

  return (
    moves.find((move) => normalize(move.strandId) === strandId) ??
    moves.find((move) => label && normalize(move.label).includes(label)) ??
    moves.find((move) => label && label.includes(normalize(move.label))) ??
    moves[0]
  );
}

export function buildSkillMoveScaffold(args: {
  standardCode: string;
  strandId?: string | null;
  strandLabel?: string | null;
  targetSkill?: string | null;
  fallbackMove: string;
}) {
  const move = getReadingSkillMove(args);
  if (!move) return `Use today's move: ${args.fallbackMove} Choose the answer that proves the standard in this passage.`;

  return [
    `Today's skill: ${move.label}.`,
    move.studentMove,
    move.scaffold,
    `Mastery means: ${move.masterySignal}`,
  ].join(' ');
}

export function getSkillMoveCoverageSummary() {
  const byStandard = ELA9_READING_SKILL_MOVES.reduce<Record<string, number>>((map, move) => {
    map[move.standardCode] = (map[move.standardCode] ?? 0) + 1;
    return map;
  }, {});

  return Object.entries(byStandard)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([standardCode, skillMoves]) => ({ standardCode, skillMoves }));
}
